### ISSUE TITLE
.NET 5 Status?

### ISSUE THREAD

**Issue by guardrex** [AzureADQuickStarts/B2C-WebApp-OpenIdConnect-DotNet#1]
None of these packages are .NET 5 Core CLR-friendly:

```
Microsoft.Owin.Security.OpenIdConnect
Install-Package Microsoft.Owin.Security.Cookies
Install-Package Microsoft.Owin.Host.SystemWeb
```

What's the status on getting an example of this for .NET 5 (a Core CLR version is what I need)?

**Comment by guardrex** [comment]
I was actually able to get the entire B2C working under .NET 5 (Core CLR) using the .NET 5 example.

**Comment by jsturtevant** [comment]
In case someone else finds this and looking for asp.net core sample: https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore-b2c
