### ISSUE TITLE
Sign in after Sign out - It just singes me in without asking username and password

### ISSUE THREAD

**Issue by priyakantpatel** [AzureADQuickStarts/B2C-WebApp-OpenIdConnect-DotNet#12]
Sign out issue!

When I "Sign in" after "Sign out" it just singes me in without asking username and password.

Steps: (I have only G+ setup at this moment and I have not made any application changes other then config values.)
1. Launch application and Click "Sign in"
2. It takes me to the Google Sign in page, where I enter username password.
3. It takes be back to the my home page and I can see it am signed
4. Click "Sign out" and I can see I am signed out from application (optionally I open another browser tab and go to Gmail and I am still logged in)
5. Click "Sign in" and it Singes me in without asking my credentials.

Am I missing any settings? Is there any way I can sign-out globally?

Thanks,

**Comment by rlarno** [comment]
This is 'By design', also see the **Note** here: https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-reference-oidc#send-a-sign-out-request

Signing-out means the auth cookie for your application is cleared, not the one of the Identity Provider (Google in your case).
