### ISSUE TITLE
Can't edit user profile

### ISSUE THREAD

**Issue by bartekkw** [AzureADQuickStarts/B2C-WebApp-OpenIdConnect-DotNet#13]
I can successfully create an account and log in. When I click [username] -> Edit profile I'm redirected to login page. I'm already logged-in, so why log-in again? But this is not the biggest problem. When I enter e-mail address - I'm asked if I want to use "Work or school" or "Personal" account. I choose "Work or school", but I can't log in! So as a result - **user can not update his/her profile**.
Should I set something special in my "b2c_1_edit_profile" policy?

**Comment by gsacavdm** [comment]
@bartekkw , I'm closing this issue since this sample has been deprecated in place of the newer [**Azure AD B2C: Call a .NET web API from a .NET web app** sample](https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi). Feel free to submit issues against that one.
