### ISSUE TITLE
OutOfMemory Exceptions

### ISSUE THREAD

**Issue by samirbittar** [AzureADQuickStarts/B2C-WebApp-OpenIdConnect-DotNet#3]
The current code has a bug that eventually throws OutOfMemory exceptions. I've tracked the bug down to `MergeConfig` method of `PolicyConfigurationManager` class.
This method is supposed to copy from "other" into "source", however it is copying "source" into "other".
Also, once you fix this, you then need to set `ValidateIssuer = false` on your `TokenValidationParameters` inside `ConfigureAuth` method of the `Startup` class. If you don't, OpenIdConnect will fail because it does not recognize the issuer of the id_token.

**Comment by n-o-r-m-a-n** [comment]
I get OutOfMemory from time to time as well. However, I don't see why you need to turn off issuer validation. Any deeper insights on this?

**Comment by samirbittar** [comment]
Turning off issuer validation is not what fixes the OutOfMemory exception. With the fix shown on the pull request, what happens is that the issuer that's returned by the token is no longer null. So you need to either specify that you do not want to validate the issuer, or specify the expected valid issuer inside your TokenValidationParameters
