### ISSUE TITLE
When cloning the skeleton branch you must update the Microsoft.IdentityModel.Protocol.Extensions package

### ISSUE THREAD

**Issue by mattcowen** [AzureADQuickStarts/B2C-WebApp-OpenIdConnect-DotNet#5]
On my cloned skeleton branch I had to update the nuget packages because I got a runtime error for Microsoft.IdentityModel.Protocol.Extensions not matching the referenced assembly. I updated Newtonsoft and System.IdentityModel.Tokens.Jwt.

**Comment by dstrockis** [comment]
Should be OK now, thanks for the issue... If anyone experiences this again please re-open
