### ISSUE TITLE
Be aware of ClaimsPrincipal.Current problem

### ISSUE THREAD

**Issue by mattcowen** [AzureADQuickStarts/B2C-WebApp-OpenIdConnect-DotNet#6]
It may be preferable to use an alternative method to retrieve a claim than that shown in the AccountController. For example, the AccountController's SignOff method uses ClaimsPrincipal.Current which, depending on your application, may not reference the principal and identity that has ALL the claims. 

If you have a problem accessing the claims in a MVC application, try casting User as ClaimsPrincipal and accessing the Identity and the claims that way....

var principal = User as ClaimsPrincipal;
var claim = principal.Identities.First().FindFirst("acr");

**Comment by dstrockis** [comment]
Good tip!
