### ISSUE TITLE
Invalid endpoint query string

### ISSUE THREAD

**Issue by TomProkop** [AzureADQuickStarts/B2C-WebApp-OpenIdConnect-DotNet#9]
Configuration endpoint
/v2.0/.well-known/openid-configuration?p=B2C_1_2

now returns endpoints with query string

`"authorization_endpoint": "https://login.microsoftonline.com/x.onmicrosoft.com/oauth2/v2.0/authorize?p=b2c_1_2"`

and _Authentication.Challenge_ redirects to 

/oauth2/v2.0/authorize**?**p=b2c_1_2**?**client_id=...

Since there are two question marks and uri is invalid it throws 404 - File or directory not found

**Comment by TomProkop** [comment]
It is working with /.well-known/openid-configuration?p=B2C_1_2 (v1) endpoint.

There is no query in the uri.

`"authorization_endpoint": "https://login.microsoftonline.com/te/x.onmicrosoft.com/b2c_1_2/oauth2/authorize"`

**Temporary workaround:**
App_Start\Startup.Auth.cs

`ConfigurationManager = new PolicyConfigurationManager(
                    String.Format(CultureInfo.InvariantCulture, aadInstance, tenant, "", OIDCMetadataSuffix),
                    new string[] { SignUpPolicyId, SignInPolicyId, ProfilePolicyId }),`

**Comment by dstrockis** [comment]
Please update to the latest versions of OWIN and the Microsoft.IdentityModel.Protocol.Extensions package to fix this problem.
